services:
  application-interview-db:
    image: postgres:17
    container_name: application-interview-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: application-service
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
    ports:
      - "5435:5432"
    volumes:
      - application-interview-db-data:/var/lib/postgresql/data

volumes:
  application-interview-db-data:
